### ISSUE TITLE
গিটহাব থেকে কিভাবে ড্যাঙ্গ প্রজেক্ট নামিয়ে কাজ করবো   ??

### ISSUE THREAD

**Issue by Yeasincse** [SabujXi/Python-Django-Webinar-In-Bangla-Season-1#1]
সবুজ ভাই আপনার গিটহাব থেকে কিভাবে প্রজেক্ট তা ফর্ক  করে  কাজ করবো.তারপর আপনার প্রজেক্ট এর ভিতর কি আবার ভার্চুয়ালভ এনভায়রনমেন্ট কি create kortae  হইবে.তারপর pycharm এই কিভাবে ওপেন করবো প্রজেক্টটা.বুজতেসি না.কারণ আমি গিটহাবে নতুন .আপনি যদি এই ব্যাপারে একটা টিউটোরিয়াল বানাইতেন , খুব উপকারে আসতো ড্যাঙ্গর  প্রজেক্ট তা আপনার গিটহাব থেকে.please এই ব্যাপারে  deatails  গিটহাব  এবং গীতের ভিতর কিভাবে করবো আলোচনা করলে ভালোই হয়তো

**Comment by SabujXi** [comment]
Cover this in today's episode: https://www.youtube.com/watch?v=FsB2op3ZVt0
