### ISSUE TITLE
এপিসোডে১ এ প্রথম থেকে স্ক্রিন শেয়ার করলে উপকৃত হইতাম এবং প্রব্লেম সল্ভ হইত

### ISSUE THREAD

**Issue by Yeasincse** [SabujXi/Python-Django-Webinar-In-Bangla-Season-1#2]
এপিসোডে১ এ ভাই প্রথম থেকে স্ক্রিন শেয়ার করলে আমার ভালো করে কাজটা করতে পারতাম | আপনি  গিটহাব সেটিং তারপর  pycharm এই প্রজেক্ট সেটিং করলেন ভালো করে বুজতে পারিনি ভাই| আবার এপিসোডে১ প্রথম থেকে পূনরা কাজ তা দেখাইলে উপকৃত হইতাম|

**Comment by SabujXi** [comment]
These things have been covered in Episode-02 (3rd episode): https://www.youtube.com/watch?v=FsB2op3ZVt0

**Comment by SabujXi** [comment]
https://www.youtube.com/watch?v=FsB2op3ZVt0
